# Tmux config

set -s escape-time 10
setw -g mode-keys vi

set -g base-index 1
set -g renumber-windows on

set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"

set -g mouse on

set -g allow-passthrough on
set -g focus-events on

set -g detach-on-destroy off

# Move between panes with h/j/k/l
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Swap panes (optional)
bind < swap-pane -U
bind > swap-pane -D

# reloaded
bind r source-file ~/.tmux.conf \; display-message "Tmux config reloaded!"

# Better Split panes | use %, "
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"
unbind '"'
unbind %

# better window
bind c new-window -c "#{pane_current_path}"

# History copy
set-option -g history-limit 10000

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Clipboard
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
